import Head from 'next/head';
import { useFetchData } from '@/hooks/useFetchData';
import Header from '@/components/layout/Header';
import { Market } from '@/types/api/market';
import ListItem from '@/components/market/listItem';
import styles from '@/styles/market/List.module.scss';
import Link from 'next/link';
// import Image from 'next/image';

export default function MarketList() {
  const { data, error, isLoading } = useFetchData('exchange/api/v1.0/exchange/pairs');
  return (
    <>
      <Head>
        <title>رمزینکس</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header>
          {/*<input className={styles.searchInput} />*/}
          {/*<button>*/}
          {/*  <Image*/}
          {/*    src="/images/icons/dark.png"*/}
          {/*    alt="theme toggler"*/}
          {/*    width={28}*/}
          {/*    height={28}*/}
          {/*    priority*/}
          {/*  />*/}
          {/*</button>*/}
        </Header>
        <main style={{ padding: '8px', paddingTop: '56px' }}>
          {isLoading && <div>Loading...</div>}
          {error && <div>Error: </div>}
          {data && (
            <ul className={styles.list}>
              {data.data.map((item: Market) => (
                <li key={item.pair_id} className={styles.listItem}>
                  <Link href={`/market/${item.pair_id}`}>
                    <ListItem market={item} />
                  </Link>
                </li>
              ))}
            </ul>
          )}
        </main>
      </div>
    </>
  );
}
