import Head from 'next/head';
import { useFetchData } from '@/hooks/useFetchData';
import Header from '@/components/market/Header';
import { Market } from '@/types/api/market';
import ListItem from '@/components/market/listItem';
import styles from '@/styles/components/market/List.module.scss';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import Loading from '@/components/uikit/Loading';

export default function MarketList() {
  const { data, error, isLoading } = useFetchData('exchange/api/v1.0/exchange/pairs');
  const [searchTerm, setSearchTerm] = useState<string>('');
  const [sortBy, setSortBy] = useState<string>('');
  const [debouncedSearchTerm, setDebouncedSearchTerm] = useState<string>('');
  useEffect(() => {
    const handler = setTimeout(() => {
      setDebouncedSearchTerm(searchTerm);
    }, 300);

    return () => {
      clearTimeout(handler);
    };
  }, [searchTerm]);

  if (isLoading) return <Loading text="در حال بارگزاری..." />;
  const filteredData = data?.data?.filter((item: Market) =>
    item.name.fa.includes(debouncedSearchTerm),
  );
  if (sortBy) {
    filteredData.sort((a: Market, b: Market) => {
      if (sortBy === 'name') {
        return a.name.fa.localeCompare(b.name.fa);
      } else {
        return +a.buy - +b.buy;
      }
    });
  }
  return (
    <>
      <Head>
        <title>رمزینکس</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header searchTerm={searchTerm} setSearchTerm={setSearchTerm} setSortBy={setSortBy} />
        <main className="main">
          {error && <div>Error: </div>}
          {data && (
            <ul className={styles.list}>
              {filteredData.map((item: Market) => (
                <li key={item.pair_id} className={styles.listItem}>
                  <Link href={`/market/${item.pair_id}`}>
                    <ListItem market={item} />
                  </Link>
                </li>
              ))}
            </ul>
          )}
        </main>
      </div>
    </>
  );
}
